#!/usr/bin/env bash
# RL-06 (+ RL-10 tombstone declaration) — bundle DRAIN-verdict findings into ONE
# GAPS_SPEC-style findings register (ID + severity + evidence + acceptance
# criterion) for `/spec --from-findings` (RL-04). This is the ONLY artifact the
# loop authors on the drain path — MARKDOWN, never a manifest and never code:
# spec-gen is the manifest's ONLY writer (HC3), autopilot writes product code.
#
# HARDENED (Defect B): the register bundles N findings into N acceptance rows and
# makes NO single-Story claim — spec-gen decides the Story decomposition (ADR 0007:
# a multi-finding register can become several Stories). GENERATE at Pickup opens
# the Runbook PR; the drain files one-or-more Story PRs; NONE are merged.
#
# HARDENED (Defect C — tombstone authored by the right writer): a drain-class
# REMOVAL that deletes a symbol (dead-code) declares the withdrawal as an
# acceptance behavior in THIS register, so spec-gen emits the
# `lifecycle: withdrawn` + `withdrawn_reason` tombstone into the manifest it owns.
# The loop never writes that tombstone itself (ADR 0018 corrects the draft's
# autopilot-writes-it wiring); CH-05 then cannot flag the loop's own cleanup as rot.
#
# Loop branch namespace: remediation/<slug>/*  (Runbook PR: remediation/<slug>/runbook;
# Story PRs: remediation/<slug>/story-N) — feeds Guard-2 self-namespace detection.
#
# Input: DRAIN findings as TAB rows on stdin (or --in <file>):
#   fingerprint <TAB> severity <TAB> slug <TAB> path <TAB> symbol [<TAB> evidence]
# Usage:  build_register.sh [--slug <loop-slug>] [--in <rows>] [--out <register.md>]
set -uo pipefail

SLUG="batch"; INFILE=""; OUTFILE=""
while [ $# -gt 0 ]; do
  case "$1" in
    --slug) SLUG="${2:-batch}"; shift 2 ;;
    --in)   INFILE="${2:-}"; shift 2 ;;
    --out)  OUTFILE="${2:-}"; shift 2 ;;
    *) echo "build_register: unknown arg: $1" >&2; exit 64 ;;
  esac
done

emit() { if [ -n "$OUTFILE" ]; then cat >> "$OUTFILE"; else cat; fi; }
[ -n "$OUTFILE" ] && : > "$OUTFILE"

{
  echo "# Remediation findings register — remediation/$SLUG"
  echo
  echo "> Auto-generated by \`/remediate\` (RL-06). REPORT-ONLY / advisory-first: this"
  echo "> register drives a \`/spec --from-findings\` session whose drain opens a Runbook"
  echo "> PR + **one-or-more** Story PRs (ADR 0007/0009) for HUMAN review. NONE are"
  echo "> merged (autopilot HC4). The loop authors NO manifest and NO code; spec-gen"
  echo "> is the manifest's only writer (HC3) and emits any \`lifecycle: withdrawn\`"
  echo "> tombstone declared below. Branch namespace: \`remediation/$SLUG/*\`."
  echo
  echo "| ID | Severity | Evidence | Acceptance criterion |"
  echo "|---|---|---|---|"
} | emit

n=0
process_row() {
  local fp="$1" sev="$2" fslug="$3" path="$4" symbol="$5" evidence="$6"
  [ -n "$fslug" ] || return 0
  n=$((n+1))
  local id; id="$(printf 'RM-%03d' "$n")"
  [ -n "$evidence" ] || evidence="finding $fp"
  local acc
  case "$fslug" in
    dead-code)
      # symbol removal → DECLARE the withdrawal so spec-gen tombstones the manifest.
      acc="Withdraw symbol \`$symbol\` from \`$path\` (lifecycle: withdrawn; withdrawn_reason: dead-code removal per finding $fp). spec-gen MUST emit the manifest tombstone; the impl diff carries no tombstone." ;;
    *)
      acc="Remediate \`$fslug\` at \`$path\`:\`$symbol\` with a regression test proving closure (verifiable downstream by the suite's own gates)." ;;
  esac
  printf '| %s | %s | %s | %s |\n' "$id" "$sev" "\`$path\`:\`$symbol\` — $fslug ($evidence)" "$acc" | emit
}

SRC="${INFILE:-/dev/stdin}"
while IFS="$(printf '\t')" read -r fp sev fslug path symbol evidence rest; do
  [ -n "${fp:-}" ] || continue
  case "$fp" in \#*) continue ;; esac
  process_row "$fp" "$sev" "$fslug" "$path" "$symbol" "${evidence:-}"
done < "$SRC"

{
  echo
  echo "_$n finding(s) bundled. Story decomposition is spec-gen's call (NOT one PR per register)._"
} | emit

# Signal count on stderr so the orchestrator can note an empty register (skip).
echo "[build_register] $n DRAIN finding(s) → register (branch namespace remediation/$SLUG/*)" >&2
